version: '2'

services:

  zammad:
    depends_on:
      - zammad-elasticsearch
      - zammad-postgresql
    image: zammad/zammad-docker-compose:zammad
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
    restart: on-failure
    volumes:
      - data-zammad:/home/zammad

  backup:
    depends_on:
      - zammad
    image: zammad/zammad-docker-compose:zammad-backup
    labels:
      io.rancher.container.pull_image: always
    links:
      - zammad-postgresql
    restart: always
    volumes:
      - data-zammad:/home/zammad
      - backup-zammad:/var/tmp/zammad

  elasticsearch:
    image: zammad/zammad-docker-compose:zammad-elasticsearch
    labels:
      io.rancher.container.pull_image: always
    restart: always
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data

  nginx:
    depends_on:
      - zammad
    image: zammad/zammad-docker-compose:zammad-nginx
    labels:
      io.rancher.container.pull_image: always
    links:
      - zammad-railsserver
      - zammad-websocket
    ports:
      - "80:80"
    restart: always
    volumes:
      - data-zammad:/home/zammad

  postgresql:
    image: zammad/zammad-docker-compose:zammad-postgresql
    labels:
      io.rancher.container.pull_image: always
    restart: always

  railsserver:
    depends_on:
      - zammad
    image: zammad/zammad-docker-compose:zammad-railsserver
    labels:
      io.rancher.container.pull_image: always
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    depends_on:
      - zammad
    restart: always
    volumes:
      - data-zammad:/home/zammad

  scheduler:
    depends_on:
      - zammad
    image: zammad/zammad-docker-compose:zammad-scheduler
    labels:
      io.rancher.container.pull_image: always
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    restart: always
    volumes:
      - data-zammad:/home/zammad

  websocket:
    depends_on:
      - zammad
    image: zammad/zammad-docker-compose:zammad-websocket
    labels:
      io.rancher.container.pull_image: always
    links:
      - zammad-postgresql
      - zammad
    restart: always
    volumes:
      - data-zammad:/home/zammad

volumes:
  backup-zammad:
    driver: local
  data-zammad:
    driver: local
  data-elasticsearch:
    driver: local
