.catalog:
  name: "Zammad"
  version: "1.2-1"
  description: "Zammad is a web based open source helpdesk/customer support system"
  uuid: zammad-1
  minimum_rancher_version: v1.2.0
  questions:

version: '2'

services:

  zammad:
    scale: 1
    start_on_create: true

  backup:
    scale: 1
    start_on_create: true

  elasticsearch:
    scale: 1
    start_on_create: true

  nginx:
    scale: 1
    start_on_create: true

  postgresql:
    scale: 1
    start_on_create: true

  scheduler:
    scale: 1
    start_on_create: true

  railsserver:
    scale: 1
    start_on_create: true

  websocket:
    scale: 1
    start_on_create: true
